name: jar analyzer build

on:
  workflow_dispatch:

env:
  VERSION: "3.1"

jobs:

  build:
    runs-on: windows-2019
    steps:
      - name: checkout the source
        uses: actions/checkout@v4
        with:
          path: jar-analyzer

      - name: set up java 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: build agent
        run: |
          Remove-Item "lib\agent.jar" -Force
          cd agent
          .\package.bat
        working-directory: jar-analyzer

      - name: build core
        run: |
          .\package.bat
        working-directory: jar-analyzer

      - name: build release
        run: |
          python .\build.py
        working-directory: jar-analyzer

      - name: copy jar
        run: |
          Copy-Item "target\jar-analyzer-${{ env.VERSION }}-jar-with-dependencies.jar" -Destination "release\jar-analyzer-${{ env.VERSION }}.jar"
        working-directory: jar-analyzer

      - name: download jre-8
        run: |
          curl -L "https://github.com/jar-analyzer/workflow_jre/releases/download/temurin-8u422/jre.zip" -o "jre-8.zip"
        working-directory: jar-analyzer

      - name: download jre-22
        run: |
          curl -L "https://github.com/jar-analyzer/workflow_jre/releases/download/temurin-22.0.2/jre.zip" -o "jre-22.zip"
        working-directory: jar-analyzer

      - name: unpack jre-8
        run: >
          unzip jre-8.zip -d release\jar-analyzer-${{ env.VERSION }}-windows-full\
        working-directory: jar-analyzer

      - name: unpack jre-22
        run: >
          unzip jre-22.zip -d release\jar-analyzer-${{ env.VERSION }}-windows-22\
        working-directory: jar-analyzer

      - name: zip release
        run: |
          dir
          Compress-Archive -Path "jar-analyzer-${{ env.VERSION }}-windows-system\" -DestinationPath "jar-analyzer-${{ env.VERSION }}-windows-system.zip" -CompressionLevel Optimal
          Compress-Archive -Path "jar-analyzer-${{ env.VERSION }}-windows-full\" -DestinationPath "jar-analyzer-${{ env.VERSION }}-windows-full.zip" -CompressionLevel Optimal
          Compress-Archive -Path "jar-analyzer-${{ env.VERSION }}-windows-22\" -DestinationPath "jar-analyzer-${{ env.VERSION }}-windows-22.zip" -CompressionLevel Optimal
          Compress-Archive -Path "jar-analyzer-${{ env.VERSION }}\" -DestinationPath "jar-analyzer-${{ env.VERSION }}.zip" -CompressionLevel Optimal
        working-directory: jar-analyzer/release
        shell: pwsh


      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-analyzer
          path: |
            jar-analyzer/release/jar-analyzer-${{ env.VERSION }}-windows-full.zip
            jar-analyzer/release/jar-analyzer-${{ env.VERSION }}-windows-22.zip
            jar-analyzer/release/jar-analyzer-${{ env.VERSION }}-windows-system.zip
            jar-analyzer/release/jar-analyzer-${{ env.VERSION }}.zip
