name: maven check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up java 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: check core maven
      run: mvn -B clean package -DskipTests --file pom.xml --file pom.xml
    - name: check agent maven
      run: cd agent && mvn -B clean package -DskipTests --file pom.xml --file pom.xml
